### PR TITLE
readme: make curl commands consistent

### PR DESCRIPTION
**Pull request by ryane**

### CODE REVIEW

**Comment by langston-barrett** [comment]
Maybe we should also have a note explaining that you can use mantl-api on a worker node? I don't know that I would assume that if all the examples are control nodes.

**Comment by ryane** [comment]
It actually always runs on a worker node (assuming it's deployed via marathon). But, on Mantl clusters, it is automatically proxied via nginx running on control nodes (along with our other control software and UIs). If you wanted to, though, you could always discover the worker node, ip, and host that is running on via Marathon and make api requests directly (assuming the port is accessible).

Maybe I'll add some text that explains how it is deployed and wired up on Mantl clusters (the fact that it's automatically accessible on control nodes). Would that help?

**Comment by langston-barrett** [comment]
I think that'd be great! I like that most of the documentation is mantl-agnostic, but I think it might be useful for people who are running this on top of mantl to have a deeper understanding of how it works.

**Comment by ryane** [comment]
@siddharthist updated, let me know if this is more clear

**Comment by langston-barrett** [comment]
Very clear :) LGTM!

**Pull request merged**
