### PR TITLE
vault

### PR DESCRIPTION
**Pull request by langston-barrett**
see https://github.com/CiscoCloud/mantl/issues/1113

tested only with vault-token

### CODE REVIEW

**Comment by langston-barrett** [comment]
this needs documentation

**Comment by langston-barrett** [comment]
This has documentation :smile:

**Comment by langston-barrett** [comment]
I'm working on some automated testing, hold off on merging for now

**Comment by ryane** [comment]
I was looking at this and it seems to be working well (I've only tested using the generic backend so far). When we deploy this, is the idea to use the `VAULT_*` env vars to configure the vault client when it is running in marathon? 

Any update on the automated testing or is this ready to merge?

**Comment by ryane** [comment]
I need some of this now so I am going to go ahead and merge

**Pull request merged**
